<script>
    async function getFakeName() {
        const res = await fetch("/api/fakename");
        const name = await res.text();

        // wait 2 seconds, just to simulate a load time
        await new Promise((res) => setTimeout(res, 2000));

        return name;
    }

    async function getFakeAddress() {
        const res = await fetch("/api/fakeaddress");
        const address = await res.text();

        // wait 2 seconds, just to simulate a load time
        await new Promise((res) => setTimeout(res, 2000));

        return address;
    }

    let namePromise = getFakeName();
    let addressPromise = getFakeAddress();
</script>

<main>
    <p>
        This frontend is written in Svelte. The name and address displayed below
        are generated by Faker and served by Python Django.
    </p>

    {#await namePromise}
        <p>getting name...</p>
    {:then name}
        <p>{name}</p>
    {/await}

    {#await addressPromise}
        <p>getting address...</p>
    {:then address}
        <p>{address}</p>
    {/await}
</main>
